### ISSUE TITLE
Transfer project to Mesos GitHub org?

### ISSUE THREAD

**Issue by rji** [mesosphere/mesos-cli#70]
Since Mesosphere has deprecated this project in favor of its DCOS CLI project, I decided to check it out. I noticed the [following disclaimer](https://github.com/mesosphere/dcos-cli/blob/778a0f1a0042c7badbdaa60afcf78fbcc48af4fa/README.rst) in the README:

> Note that the DCOS CLI has tight integration with DCOS and certain functionality may not work as expected or at all when using it directly with Mesos and Marathon.

I'm not sure if Mesosphere is open to this, but I think it might make sense to transfer this 'mesos' GitHub org so the community can continue maintaining it. It'd be unfortunate if the tool became fragmented, or if the community duplicated efforts, as people forked this repo and started maintaining private forks.

Thoughts?

**Comment by ssk2** [comment]
@rji - thanks for the suggestion! 

There was actually some effort underway last year to move this into the Mesos codebase but there were some concerns raised about the sheer volume of additional code and ultimately they decided to keep it separate :). 

We're planning on bringing the DCOS CLI up to parity with the Mesos CLI so that it supports all of the same commands (and some very cool new ones too). The functionality that won't work without DCOS is functionality that is currently not in the Mesos CLI - so there's no "loss" per se. It is also now open source and we'd love increased community involvement there.

Does that address your concerns? We're still working on better documentation for the CLI, so I'll be sure to update the README there!

**Comment by rji** [comment]
Hey @ssk2 – thanks for the reply. That definitely helps; from the note in the readme, I wasn't sure what would be missing from the DCOS CLI, but I'm glad to hear that there's no net loss. I'll check it out!

-- Roger
