### ISSUE TITLE
Extremely disappointed in Mesosphere

### ISSUE THREAD

**Issue by sleaze** [mesosphere/mesos-cli#71]
It's a big disappointment that Mesosphere has discontinued support for this this project - the dcos client forces you to register with mesosphere even if you just want to use the tool on your own cluster on your own private network.

Shame! Shame on YOU Mesosphere.

**Comment by ssk2** [comment]
Hi @sleaze, thanks for the issue! You're welcome to continue using this tool if you like, we're just putting our limited development effort into the DCOS CLI. There were too few users of this tool (at least while it was actively being maintained) to justify continued support.

The registration step of the DCOS client is optional and if you simply hit enter without pasting in a token, you'll find it works just fine. We're working on improving the messaging in the installer script so that this is more obvious.

**Comment by sleaze** [comment]
But why must I register for dcos to use it on my LAN?
